### PR TITLE
Fix Net::SSLeay version

### PR DESCRIPTION
**Pull request by Rid**
Also having this issue with Net::SSLeay 1.84.

### CODE REVIEW

**Comment by thebigmunch** [comment]
If you're having the issue with 1.84, shouldn't the condition be ``> 1.84``, not ``>=1.84``?

Has this been determined/tested to be the correct version in the issue related to this?

**Comment by Rid** [comment]
1.84 requires `Net::SSLeay::ssl_read_all()`

**Comment by thebigmunch** [comment]
> 1.84 requires `Net::SSLeay::ssl_read_all()`, and 1.84 is the default shipped with Ubuntu 18.04, to work around it we upgraded `Net::SSLeay` to 1.88 but others are probably still facing this issue.

You said:

> Also having this issue with Net::SSLeay 1.84.

So, sounds like you just mispoke there?

More important is if this is actually the minimum version that requires ``Net::SSLeay::ssl_read_all()``.

**Comment by Rid** [comment]
It looks like `Net::SSLeay::ssl_read_all()` has been included since at least 1.03:

https://metacpan.org/changes/release/MIKEM/Net-SSLeay-1.37

You can see in the change log:
```
1.03  4.1.1999, Sampo Kellomaki <sampo@@iki._fi>
        - Merged URI encoding patch to make_form
          from Joe Rhett <jrhett@@navigist._com>
        - changed sslcat, ssl_read_all, ssl_write_all to return error messages
          as second member of list. Functions continue to behave the old way
          if scalar return value is used (they check this with wantarray).
          Change was suggested by Joe Rhett.
```

So it's probably fine to just use `Net::SSLeay::ssl_read_all()` by default.

**Comment by thebigmunch** [comment]
> So it's probably fine to just use `Net::SSLeay::ssl_read_all()` by default.

Nope. The issue wasn't about the function existing, but something changing about it that fails with versions before ____. I forgot that fact when I hurriedly released 2.6. I didn't have time to do any kind of exhaustive search for the exact point where things failed and needed to release some kind of a fix quick, so I used the oldest version I had at hand (1.86). Another user had 1.72 and said that didn't work with ``ssl_read_all``. So, it would seem somewhere between those 2 numbers is the correct answer. I could probably use 1.84 instead, and it would be pretty effective even if it's not the correct tipping point. But I'd actually be interested in knowing the right point at which this changed.

**Comment by Rid** [comment]
The only changes I can find in the changelog to `Net::SSLeay::read` are:

```
1.49 2012-09-25
Improvements to Net::SSLeay::read to make it easier to use with non-blocking IO:
      contributed by James Marshall:  It modifies
      Net::SSLeay::read() to return the result from SSL_read() as the second
      return value, if Net::SSLeay::read() is called in list context.  Its
      behavior should be unchanged if called in scalar or void context.  This
      result code seems to be required for full support of non-blocking I/O,
      since users need to handle SSL_ERR_WANT_READ, SSL_ERROR_WANT_WRITE, etc.
```

and 

```
1.86_06 2018-09-29
        - Net::SSLeay::read() and SSL_peek() now check SSL_get_error()
          for SSL_ERROR_ZERO_RETURN for return values <= 0 to make
          Net::SSLeay::read() behave more like underlying OpenSSL
          function SSL_read().
          Convenience function ssl_read_all() now does an automatic
          retry when ERROR_WANT_READ or ERROR_WANT_WRITE is returned
          with Net::SSLeay::read().
          Convenience function ssl_read_until() now uses
          Net::SSLeay::ssl_read_all() instead of
          Net::SSLeay::read(). Tests 07_sslecho.t and 36_verify.t were
          also updated to use ssl_read_all() and ssl_write_all(). The
          tests now also disable TLSv1.3 session tickets and ignore
          SIGPIPE to avoid this signal when the client has finished
          before server has sent session tickets and called
          Net::SSLeay::accept().
          Thanks to Petr Pisar and Sebastian Andrzej Siewior for the
          patches (in #RT125218).
```

So maybe the change was undocumented?

**Comment by thebigmunch** [comment]
Very well could be. Those were also the only changes I saw when I took a quick glance, which reinforced my choosing of 1.86 at the time. But, like most things Perl, the Net::SSLeay changelog is a clusterfuck.

I'll still change it to 1.84 since I now know that's the version shipped with Ubuntu 18.04. That will probably curtail the problem for most users.

**Comment by koblack** [comment]
On my Ubuntu 18.04.2 LTS autodl stopped working after upgrade

`2019-08-21 06:29:52 upgrade libnet-ssleay-perl:amd64 1.84-1build1 1.84-1ubuntu0.2`

difference between `1.84-1build1` and `1.84-1ubuntu0.2` are cherrypicked patches from 1.85-2 for OpenSSL 1.1.1 support

https://launchpadlibrarian.net/438157628/libnet-ssleay-perl_1.84-1build1_1.84-1ubuntu0.2.diff.gz

```
libnet-ssleay-perl (1.84-1ubuntu0.2) bionic-security; urgency=medium

  * No-change rebuild in -security pocket now that OpenSSL 1.1.1 is
    available.

 -- Marc Deslauriers <marc.deslauriers@ubuntu.com>  Tue, 20 Aug 2019 08:47:00 -0400

libnet-ssleay-perl (1.84-1ubuntu0.1) bionic; urgency=medium

  * Cherrypick patches prepared by Damyan Ivanov from 1.85-2 for OpenSSL
    1.1.1 support (LP: #1797386):
    + add five patches from fedora
    + patch openssl version check about SSL_CTX_set_num_tickets existence
    + add SSL[_CTX]_(set|get)_security_level routines
    + tests: set security level to 1 when loading certificates with small keys
    + patch set_cert_and_key to not return error when none of the underlying
      routines does

 -- Dimitri John Ledkov <xnox@ubuntu.com>  Tue, 04 Dec 2018 14:05:51 +0000

libnet-ssleay-perl (1.84-1build1) bionic; urgency=medium
```

source https://launchpad.net/ubuntu/+source/libnet-ssleay-perl

**Pull request closed without merging**
